      
name: 'Get & Cache dependecies'
description: 'Get dependencies (via npm) and cache them.'
runs:
  using: 'composite'
  steps:
    - name: Cache dependencies
      id: cache
      uses: actions/cache@v3 # caching the dependencies
      with:
        path: ~/.npm # npm will know that is a dependencie cache
        key: deps-node-modules-${{ hashFiles('**/package-loc.json') }} # whenever the file change the hash will change thus the dependencie folder will be re install
    - name: Install dependencies
      run: npm ci
      shell: bash