name: Test project
on: push # whenever a new push comes to the repository
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3 # this is a community action that download code
      #- #name: Install nodejs #ubuntu already install nodejs
        #uses: actions/setup-node@v3
        #with: 
        #  node-version: 22.15
      - name: Install dependencies
        run: npm ci # this is more safe than npm install

      - name: Run test
        run: npm run test
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3 # this is a community action that download code
      #- #name: Install nodejs #ubuntu already install nodejs
        #uses: actions/setup-node@v3
        #with: 
        #  node-version: 22.15
      - name: Install dependencies
        run: npm ci # this is more safe than npm install
      - name: Build project
        run: npm run build
      - name: Deploy
        run: echo "Deploying ...."